name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout sources
        use: actions/checkout@v2
      - name: Install Node.js
        use: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
